### ISSUE TITLE
platformio/toolchain-esp32ulp problem

### ISSUE THREAD

**Issue by martin8310** [syssi/esphome-atorch-dl24#17]
Hello, it is not possible to install this coder on an esp32 with ESPHome v2022.5.1 `Error: Could not find the package with 'platformio/toolchain-esp32ulp @ 2.80200' requirements for your system 'linux_aarch64'` occurs. Do you know why? Regards Martin

**Comment by syssi** [comment]
The toolchain isn't arm64 compatible at the moment. Please don't use your Raspberry Pi to build the firmware. Pick a x86 machine and it should build fine!
