### ISSUE TITLE
DL24P not work Minus and Plus key

### ISSUE THREAD

**Issue by rdaguerre** [syssi/esphome-atorch-dl24#57]
thanks you.. 
Very good job!!!

Ronnie

**Comment by syssi** [comment]
If you use the `minus`/`plus` button do you see warnings/errors at the log? Please keep in mind settings cannot be adjusted directly. You have to navigate to a setting first and enter the "edit mode" to be able to increase/decrease the value using the +/- button. In other words: The feature is pretty useless if you don't sit next to your dummy load.
