### ISSUE TITLE
voltage value is rounded

### ISSUE THREAD

**Issue by man55** [syssi/esphome-atorch-dl24#85]
If you look at the device screen, the voltage is 3.352v and varies slightly. 
But through integration into the HA I see only 3.3v, which is a too rounded value, and this makes the integration essentially useless since I need to track the discharge of the LFP cell.

I don't know what exactly the problem is.
Is there any way to fix this?

![IMG_0629](https://github.com/user-attachments/assets/1374dbc3-a5fd-43a1-a1fb-92f674d137b9)
![IMG_0630](https://github.com/user-attachments/assets/4aed2acf-1191-4995-9930-3cb3753a70ce)

p.s. Another question: is it possible to add external temperature to the integration?

**Comment by syssi** [comment]
Does this feedback help: https://github.com/syssi/esphome-atorch-dl24/discussions/84

**Comment by syssi** [comment]
> p.s. Another question: is it possible to add external temperature to the integration?

You can add any (ESPHome supported) temperature sensor to the YAML.

**Comment by syssi** [comment]
> But through integration into the HA I see only 3.3v, which is a too rounded value, and this makes the integration essentially useless since I need to track the discharge of the LFP cell.

The payload of the bluetooth notification frame doesn't provide a better resolution. See https://github.com/syssi/esphome-atorch-dl24/blob/main/docs/protocol-design.md#dc-meter-report
